### ISSUE TITLE
Excessive logging

### ISSUE THREAD

**Issue by jindrichmynarz** [comsode-uv-plugins/t-geonamesOrgToRdfFile#1]
For each parsed line the DPU logs `XMLReader initialized using JAXP: com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParse...`, which, due to the size of Geonames.org, can create several GBs of logs. It might be better if this was not logged or a higher log level was used than what is the default UV log level.

I use c9d4d98750441233c61b5e3782a703fa21a9bc85 from the develop branch.

**Comment by ghost** [comment]
OK, please in future, try to past as large chunk of logs as possible. At least whole line (from which the LogLevel should be recognizable).

**Comment by jindrichmynarz** [comment]
An example of a complete line from the log is:

```
2015-05-13 18:51:39,349 [dpu: uv-t-geonamesOrgToNTriples] DEBUG exec:16 dpu:30 org.xml.sax.XMLReader - XMLReader initialized using JAXP: com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser@40026c4a
```

**Comment by ghost** [comment]
This seems unresolvable from DPU.
According to http://stackoverflow.com/questions/2621701/setting-log-level-of-message-at-runtime-in-slf4j one cannot change loglevel using slf4j. DPU cannot see logback backend.
Loglevel for backend and pipelineexecution is set in logback.xml (backend) and runtime for pipelineexecution (this message should be logged only if you run pipeilne in debug mode).
The message is logged inside  info.aduna.xml.XMLReaderFactory:89 but it is interesting that they use the:
final Logger logger = LoggerFactory.getLogger(XMLReader.class); 
XMLReader logger, not their own. Maybe you may rise a bug at rdf4j for this practice. Maybe it is common practice around XMLReader class. I dont know.
But, even if we could change the log level programatically for XMLReader logger, i would not guarantee you, that in case of XML errors, you will see proper messages. If we filter the debug level out, maybe, in case of errors, you will be missing "what went wrong while XML parsing" messages.
There are 10113356 XML files parsed in this pipeline, each message has 200 bytes, the log should be approx: 10113356*200/1024/1024/1024 = 2GB of logs:(

But the underlying XMLParser  is created for each call of org.openrdf.rio.rdfxml.RDFXMLParser.parse method. Which is also a " bug" of rdf4j, as I can see, parse method instantiates and configures the XMLParser and then calls parse method on it. Each time you parse a file. Only properties:

```
    documentURI = inputSource.getSystemId();
        saxFilter.setDocumentURI(documentURI);
```

are dependend on input of parse method (InputSource inputSource). So this is probably the best place to fill a bug against Rio library - please try to reuse XMLReader instance between RDFXMLParser.parse method calls. We can offer pull request for them...

**Comment by ghost** [comment]
just note where to find sources:https://bitbucket.org/openrdf/sesame/src/122f27c96b7d4819e07f139b5fb6e40085bbaca6/core/rio/rdfxml/src/main/java/org/openrdf/rio/rdfxml/RDFXMLParser.java?at=2.7.x#cl-276

**Comment by ghost** [comment]
just note where to find issue tracker https://openrdf.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=SES

**Comment by jindrichmynarz** [comment]
If someone should report this issue, it should be done by you, because you are familiar with Sesame, while I'm not.

**Comment by hanecak** [comment]
Note: https://github.com/UnifiedViews/Core/issues/362 may help alleviate the problem, once implemented.

But if this problem persists and causes significant problems, please reopen.

**Comment by ghost** [comment]
I have pushed one commit https://github.com/comsode-uv-plugins/t-geonamesOrgToNTriples/commit/6ca3d062f174f71ecc997a5754baac0159d974d4
which hides all logs.

**Comment by jindrichmynarz** [comment]
OK, but why the DPU now has an empty "DPU configuration" tab in its dialog?

**Comment by ghost** [comment]
Because of this
https://github.com/comsode-uv-plugins/t-geonamesOrgToNTriples/commit/61270054e5a5a6da71ed256fac8349b27d37c7ad
it would be great if we know package names and dpu names in advance of 
real implementation. As this DPU has no configuration, you can remove it 
from pipeline, delete from UV and re-create and re-insert on pipeline.

**Comment by skrchnavy** [comment]
@jindrichmynarz we are in develop branch so we don't support migration of configuration from one snapshot version to another snapshot version.

**Comment by jindrichmynarz** [comment]
Sure, I removed the previous version of this DPU before uploading the new version and finding out about this issue. The issue I reported is that if I use the current version of this DPU, there's an empty tab "DPU configuration" in its dialog. This made me wonder if it should indeed be empty or if there needs to be a table if it's empty.

**Comment by skrchnavy** [comment]
based on code, dialog is empty, @mkl-eea-sk why?

**Comment by ghost** [comment]
? this dpu is supposed to have some configuration ?

**Comment by skrchnavy** [comment]
If not then there shall not be config dialog and then there will not be empty tab.

**Comment by ghost** [comment]
Regarding excessive logging - using some hacks, I have removed the message-per-file logging. DPU now doesn't log anything.
Regarding Vaadin dialog- fixed.

Regarding raising a bug to Sesame - i have solution prepared, when enough time is available, i will create the bug and propose solution.

**Comment by skrchnavy** [comment]
Status not clear; it has label invalid but based on comment above there are some fixes / workarounds done. Issue is not closed so what is expected here to be done?

**Comment by jindrichmynarz** [comment]
This is fixed and the issue is closed. However, a proper solution would require patching Sesame, which we postponed (@mkl-eea-sk may prepare a pull request if there's time).
