### ISSUE TITLE
Repository name is inconsistent with the DPU name

### ISSUE THREAD

**Issue by jindrichmynarz** [comsode-uv-plugins/t-geonamesOrgToRdfFile#3]
The name of this repository is t-geonamesOrgToTriples, whereas the name of this DPU is t-geonamesOrgToNTriples. The names should be the same.

**Comment by skrchnavy** [comment]
Repository renamed, be aware of side effects of this change. (My experience showas that github remebers old names but not sure if it is persistent)

**Comment by skrchnavy** [comment]
you can check  original name https://github.com/comsode-uv-plugins/t-geonamesOrgToTriples if it wirks

**Comment by jindrichmynarz** [comment]
Because of problems with character encoding in serialization to N-Triples by Sesame, which doesn't support non-ASCII characters in the version used by UnifiedViews, we decided to switch to Turtle serialization (see [here](https://github.com/comsode-uv-plugins/t-geonamesOrgToNTriples/blob/develop/src/main/java/eu/comsode/unifiedviews/plugins/transformer/geonamesorgtontriples/GeonamesOrgToNTriples.java#L59)), so we may either rename the repository to t-geonamesOrgToTurtle or wait until UnifiedViews adopts a newer version of Sesame and switch back to N-Triples serialization (with correct handling of non-ASCII).

**Comment by ghost** [comment]
if this problem persists, please assign it to pgo

**Comment by skrchnavy** [comment]
@jindrichmynarz should we rename this to t-geonamesOrgToRdfFile ? (and user then can select type of serialization (support of N-Triples and Turtle as starting options).
Or another idea?

DPU have to be renamed accordingly.

**Comment by jindrichmynarz** [comment]
@mkl-eea-sk: As we discussed on the [latest commit](https://github.com/comsode-uv-plugins/t-geonamesOrgToNTriples/commit/0282904f5c8b118bd85a9fa8c84cf1c10b51ea30), there's still a problem with incorrect encoding. Should I create a new issue?

@skrchnavy: That's a good idea. I think adding 1 select box to configuration that enables the user to choose a desired serialization should be easy.

**Comment by ghost** [comment]
It has to be assigned in internal issue tracker for pgo to not forget on 
this. Go for internal issue tracker and create issue for him.

**Comment by skrchnavy** [comment]
@jindrichmynarz please create issue here to describe what doesn't work in N-Triples
