### ISSUE TITLE
Rename the DPU to match the produced output

### ISSUE THREAD

**Issue by jindrichmynarz** [comsode-uv-plugins/t-geonamesOrgToRdfFile#5]
We should rename the DPU because it no longer produces N-Triples, but Turtle instead ([see here](https://github.com/comsode-uv-plugins/t-geonamesOrgToNTriples/blob/develop/src/main/java/eu/comsode/unifiedviews/plugins/transformer/geonamesorgtontriples/GeonamesOrgToNTriples.java#L59)). The new name could be "t-geonamesOrgToTurtle" or "t-geonamesOrgToRdf" (if we decide to add another RDF serializations later, provided that it won't make users expect it to produce RDFDataUnit).

**Comment by skrchnavy** [comment]
Also repository must be renamed

**Comment by skrchnavy** [comment]
#7 describes this requirement, so marled duplicate and closing
