### ISSUE TITLE
To support different output formats (serialisation)

### ISSUE THREAD

**Issue by skrchnavy** [comsode-uv-plugins/t-geonamesOrgToRdfFile#6]
Created as a result of discussion in #3 

DPU to be extended to generate files using different serialisation. Currently N-Triples are used, it shall support in first step also Turtle.

Proposed implementation:
- User selects type of serialisation from combo box
- default serialisation is N-Triples
- Extensible for further types, it means, format of serialised DPU configuration will be kept to keep backward compatibility.

**Comment by skrchnavy** [comment]
Depends on #7

**Comment by pgo-eea-sk** [comment]
Combobox added to choose RDF format for serialization. Commit: 2623576ae3a3f6256771e894828501fade3cdcfd

**Comment by pgo-eea-sk** [comment]
Only TURTLE and NTRIPLES formats are valid in combobox. Commit 9eaeb2f4cee0f32f5613fd5c7c6aeee7248b7023

**Comment by skrchnavy** [comment]
:thumbsup: :star2: :sunny:
@jindrichmynarz to verify. it is in PR #10

**Comment by jindrichmynarz** [comment]
I've rerun a pipeline with 9eaeb2f4cee0f32f5613fd5c7c6aeee7248b7023 and it works fine. Closing the issue for now.
