### ISSUE TITLE
DPU to be renamed to t-GeonamesOrgToRdfFile

### ISSUE THREAD

**Issue by skrchnavy** [comsode-uv-plugins/t-geonamesOrgToRdfFile#7]
As a result of discussion in #3 and also related to #6 it is proposed to rename DPU to

``` T-GeonamesOrgToRdfFile```
Also repository shall be renamed accordingly
```

**Comment by pgo-eea-sk** [comment]
DPU was renamed from t-GeonamesOrgToNTriples
 to t-GeonamesOrgToRdfFile. Commit f279a0dc35fd82be4cb1594d282623b26c09c20d

**Comment by skrchnavy** [comment]
PR #10 implements this. TO finalize this issue, ale repository have to be renamed.

**Comment by skrchnavy** [comment]
Repository renamed, closed
