### ISSUE TITLE
Wrong encoding of non-ASCII characters in the DPU's output

### ISSUE THREAD

**Issue by jindrichmynarz** [comsode-uv-plugins/t-geonamesOrgToRdfFile#8]
As brought in #3, the DPU produces wrong encoding of non-ASCII characters.@mkl-eea-sk attempted to fix this in 0282904f5c8b118bd85a9fa8c84cf1c10b51ea30, the issue persists as discussed on the [commit page](https://github.com/comsode-uv-plugins/t-geonamesOrgToNTriples/commit/0282904f5c8b118bd85a9fa8c84cf1c10b51ea30#commitcomment-11407719). 

For example, while the DPU's jUnit tests pass, the DPU's output looks like the following:

```
<http://sws.geonames.org/1/> a gn:Feature ;
        rdfs:isDefinedBy <http://sws.geonames.org/1/about.rdf> ;
        gn:name "K��h-e Zardar" ;
```

Context:

```
$ echo $LANG
C
$ echo $LC_ALL
en_US.UTF-8
```

**Comment by pgo-eea-sk** [comment]
Input file read encoding changed to "UTF-8". Commit 7b3a7ffa216ad9a223598c10a0cbd7d7c1f319a8

**Comment by jindrichmynarz** [comment]
I can confirm this change fixes the encoding problems.
